### PR TITLE
Soen83 tests for login backend

### PR DESCRIPTION
**Pull request by jfv-2000**
# Description

Implements/fixes [SOEN-83](https://soen390team8.atlassian.net/jira/software/projects/SOEN/boards/1/backlog?selectedIssue=SOEN-82)

- Implementation of unit tests for back-end routes of register functionality
- Implementation of unit tests for back-end routes of login functionality
- Modification of Database: Delete & Update On Cascade for the Patient table

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit tests

# Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### CODE REVIEW

**Review by SergioAAI — APPROVED** [review]
Nice resilience , good job on the tests

**Review by NicholasYip — APPROVED** [review]
malphire r unstoppable force

**Comment by jfv-2000** [comment]
> 

rock solid !

**Review by KelvinTrang — APPROVED** [review]
Good work Muchu !

**Pull request merged**
