### PR TITLE
Delete seleniumTests directory

### PR DESCRIPTION
**Pull request by silentswordxv**
to safeguarrd steven's email

# Description

Delete file with sensitive information

## Type of change

DELETE

### CODE REVIEW

**Review by jfv-2000 — APPROVED** [review]
nice

**Review by NicholasYip — APPROVED** [review]
wowowow

**Review by amqkv — APPROVED** [review]
Noice

**Review by SergioAAI — APPROVED** [review]
Nice catch

**Review by SergioAAI — APPROVED** [review]

**Review by KelvinTrang — APPROVED** [review]
nice

**Pull request merged**
