### PR TITLE
Eslint prettier rules

### PR DESCRIPTION
**Pull request by SergioAAI**
# Description

Implements/fixes N/A

- Added typescript ESlint rules for the front end and the airbnb ESlint config for the backend.
- Added prettier eslint config so it disables rules that conflict with prettier.
- Modified some of the eslint rules so it is less annoying.
- Fixed errors the popped up with the new rules, left some of the warning to be changed if needed.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Changes to the code shouldn't break any of the features. 

N/A

# Screenshots

N/A

# Notes

Make sure the ESlint vs code extension is installed , as well as prettier.

Add

  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },

to the vs code settings json file to fix some of the linting errors that pop up.

### CODE REVIEW

**Comment by raisa61** [comment]
Code looks good!

**Review by raisa61 — APPROVED** [review]
Code looks good!

**Review by jfv-2000 — APPROVED** [review]
ESlint, more ES LITTTTTT !!  good job !

**Review by NicholasYip — APPROVED** [review]
juicy changes!

**Review by stevenvuong00 — APPROVED** [review]
nice refactor, looks good. Good work!

**Review by amqkv — APPROVED** [review]
gucci

**Pull request merged**
