### PR TITLE
Soen 14 health official dashboard

### PR DESCRIPTION
**Pull request by SergioAAI**
# Description

Implements/fixes [SOEN-14](https://soen390team8.atlassian.net/browse/SOEN-14)

- Added status swiper and chart to the modal to see previous statuses
- Adapted the charts component used in the doctor dashboard for the health official dashboard

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit tests

# Screenshots

image
 |
image

### CODE REVIEW

**Review by KelvinTrang — APPROVED** [review]
Good work guys !!

**Review by NicholasYip — APPROVED** [review]
High quality work like usual!

**Review by silentswordxv — APPROVED** [review]
Good work. If possible, can you merge main in first and update the failing test?

image

It'll be simpler than making a PR for a one line change I think

**Comment by SergioAAI** [comment]
> Good work. If possible, can you merge main in first and update the failing test?
> 
> image
> 
> It'll be simpler than making a PR for a one line change I think

**Pull request merged**
