### PR TITLE
deploys deez nuts

### PR DESCRIPTION
**Pull request by jfv-2000**
-deployment changes and ui bug fixes
-allow patient to access quarantine information page and patients tacking form even when negative
-change doctor hardcoded name to the one in database in forms to fill

Implements/fixes [SOEN-171](https://soen390team8.atlassian.net/jira/software/projects/SOEN/boards/1?selectedIssue=SOEN-171)

- changes made for deployment
- ui fixes

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by KelvinTrang — APPROVED** [review]
Good work!

**Review by NicholasYip — APPROVED** [review]
amazing

**Review by amqkv — APPROVED** [review]
Sheeeeeeesh😩🥶💯

**Review by stevenvuong00 — COMMENTED** [review]
great work as always mister jean

**Pull request merged**
