### PR TITLE
Did login page with yip and navbar

### PR DESCRIPTION
**Pull request by KelvinTrang**
Check navbar and login page, please. Completed work with yip.

### CODE REVIEW

**Review by silentswordxv — APPROVED** [review]
tested locally, works good. Nice colors.

**Review by silentswordxv — APPROVED** [review]
Checked changes, looks good.

**Comment by stevenvuong00** [comment]
checked, and tested locally, looks good

**Review by jfv-2000 — APPROVED** [review]

**Review by stevenvuong00 — APPROVED** [review]
looks really great, good job.

**Review by SergioAAI — APPROVED** [review]
Great Job

**Pull request merged**
