### PR TITLE
Soen78 navbar footer implementation

### PR DESCRIPTION
**Pull request by NicholasYip**
worked with @stevenvuong00 
it seems we had issues with prettier and a bunch of files were changed, afaik sergio is working on a fix

# Description

Implements/fixes [SOEN-#](URL to Jira ticket)

- dynamic navbar according to role
- footer
- tests for written components

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] Unit Text

# Screenshots

image

### CODE REVIEW

**Review by KelvinTrang — APPROVED** [review]
I tested it and it works well. Good job!

**Review by silentswordxv — APPROVED** [review]
I've applied some CSS fixes to the page layout so it looks nice:

image

As you can see, the footer is now properly placed at the bottom.
I've also made the navbar stick for ease of navigation.

I've run the test manually, with everything passing and obviously have successfully loaded the component locally. 

Good work.

**Review by silentswordxv — APPROVED** [review]
I've dealt with the merge conflict and fixed the resulting issues.

I've also fixed the CI error for your tests so now you get to have a nice green checkmark 👍

**Comment by silentswordxv** [comment]
> I've applied some CSS fixes to the page layout so it looks nice:
> 
> image
> 
> As you can see, the footer is now properly placed at the bottom. I've also made the navbar stick for ease of navigation.
> 
> I've run the test manually, with everything passing and obviously have successfully loaded the component locally.
> 
> Good work.

**Review by jfv-2000 — APPROVED** [review]
Looks good ! Nice tests

**Pull request merged**
