### PR TITLE
Added main page description

### PR DESCRIPTION
**Pull request by KelvinTrang**
# Description

Implements/fixes [SOEN-170](https://soen390team8.atlassian.net/browse/SOEN-170)

- Added website description main page

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
No test needed

# Screenshots
image

### CODE REVIEW

**Review by stevenvuong00 — APPROVED** [review]
thank you for your service mr bing bong

**Review by jfv-2000 — APPROVED** [review]
A real poet 
guy-fieri-chefs-kiss
!

**Review by NicholasYip — APPROVED** [review]
shakespeare

**Review by amqkv — APPROVED** [review]
Moliere🥸

**Pull request merged**
