### PR TITLE
ts config fix

### PR DESCRIPTION
**Pull request by NicholasYip**
# Description

Implements/fixes [SOEN-#](URL to Jira ticket)

- ts config fix

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

### CODE REVIEW

**Review by jfv-2000 — APPROVED** [review]
Impressive work !!!!

**Review by KelvinTrang — APPROVED** [review]
Good job. Great work!

**Review by silentswordxv — APPROVED** [review]
good point 👍

**Review by amqkv — APPROVED** [review]
Beautiful use of punctuation🤌

**Pull request merged**
